#!/usr/bin/env bash
set -euo pipefail

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(cd "$(dirname "${SCRIPT_PATH}")" && pwd)"

LAN_HOST_DEFAULT="${LAN_HOST_DEFAULT:-192.168.88.224}"

export FLEXRIC_AGENT_PORTAL_HOST="${FLEXRIC_AGENT_PORTAL_HOST:-0.0.0.0}"
export XAPP_RPC_HOST="${XAPP_RPC_HOST:-0.0.0.0}"
export MCP_HOST="${MCP_HOST:-0.0.0.0}"

export FLEXRIC_AGENT_PORTAL_PUBLIC_HOST="${FLEXRIC_AGENT_PORTAL_PUBLIC_HOST:-${LAN_HOST_DEFAULT}}"
export XAPP_RPC_PUBLIC_HOST="${XAPP_RPC_PUBLIC_HOST:-${FLEXRIC_AGENT_PORTAL_PUBLIC_HOST}}"
export MCP_PUBLIC_HOST="${MCP_PUBLIC_HOST:-${FLEXRIC_AGENT_PORTAL_PUBLIC_HOST}}"

exec "${SCRIPT_DIR}/run_agent_portal_stack.sh" "$@"
