if(NOT DEFINED INPUT_FILE)
  message(FATAL_ERROR "INPUT_FILE is required")
endif()

if(NOT DEFINED PYTHON_VERSION_MAJOR OR NOT DEFINED PYTHON_VERSION_MINOR)
  message(FATAL_ERROR "PYTHON_VERSION_MAJOR and PYTHON_VERSION_MINOR are required")
endif()

file(READ "${INPUT_FILE}" XAPP_SDK_PY)
string(REPLACE "FLEXRIC_PYTHON_VERSION_MAJOR" "${PYTHON_VERSION_MAJOR}" XAPP_SDK_PY "${XAPP_SDK_PY}")
string(REPLACE "FLEXRIC_PYTHON_VERSION_MINOR" "${PYTHON_VERSION_MINOR}" XAPP_SDK_PY "${XAPP_SDK_PY}")
file(WRITE "${INPUT_FILE}" "${XAPP_SDK_PY}")
